cmake_minimum_required(VERSION 3.28)
project(ProyectoTaller)

set(CMAKE_CXX_STANDARD 14)

include_directories(src)

add_executable(ProyectoTaller
        src/Matrix.cpp
        include/Matrix.h
        src/Mjday.cpp
        include/Mjday.h
        src/Frac.cpp
        include/Frac.h
        src/gmst.cpp
        include/gmst.h
        EKF_Test.cpp
        src/R_x.cpp
        include/R_x.h
        include/Sat_const.h
        EKF_GEOS3.cpp
        src/R_y.cpp
        include/R_y.h
        src/R_z.cpp
        include/R_z.h
        src/Legendre.cpp
        include/Legendre.h
        src/TimeUpdate.cpp
        include/TimeUpdate.h
        src/Position.cpp
        include/Position.h
        src/MeasUpdate.cpp
        include/MeasUpdate.h
        src/sign_.cpp
        include/sign_.h
        src/AccelPointMass.cpp
        include/AccelPointMass.h
        src/Mjday_TDB.cpp
        include/Mjday_TDB.h
        src/angl.cpp
        include/angl.h
        src/Cheb3D.cpp
        include/Cheb3D.h
        src/MeanObliquity.cpp
        include/MeanObliquity.h
        src/NutAngles.cpp
        include/NutAngles.h
        src/AccelHarmonic.cpp
        include/AccelHarmonic.h
        include/global.h
        src/global.cpp
        src/G_AccelHarmonic.cpp
        include/G_AccelHarmonic.h
        include/JPL_Eph_DE430.cpp
        include/JPL_Eph_DE430.h
        src/EqnEquinox.cpp
        include/EqnEquinox.h
        src/gast.cpp
        include/gast.h
        src/unit.cpp
        include/unit.h
        src/gibbs.cpp
        include/gibbs.h
        src/hgibbs.cpp
        include/hgibbs.h
        src/elements.cpp
        include/elements.h
        src/LTC.cpp
        include/LTC.h
        src/GHAMatrix.cpp
        include/GHAMatrix.h
        src/PoleMatrix.cpp
        include/PoleMatrix.h
        src/NutMatrix.cpp
        include/NutMatrix.h
        src/PrecMatrix.cpp
        include/PrecMatrix.h
        src/timediff.cpp
        include/timediff.h
        src/Geodetic.cpp
        include/Geodetic.h
        src/doubler.cpp
        include/doubler.h
)
